kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - boyvinall/linuxkit/init:latest
  - boyvinall/linuxkit/runc:latest
  - boyvinall/linuxkit/containerd:latest
  - boyvinall/linuxkit/ca-certificates:latest
onboot:
  - name: sysctl
    image: boyvinall/linuxkit/sysctl:latest
  - name: dhcpcd
    image: boyvinall/linuxkit/dhcpcd:latest
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: boyvinall/linuxkit/getty:latest
    env:
     - INSECURE=true
  - name: rngd
    image: boyvinall/linuxkit/rngd:latest
  - name: nginx
    image: nginx:1.19.5-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
files:
  - path: etc/linuxkit-config
    metadata: yaml
